version: '3.3'

services:

    vocechat:
        image: privoce/vocechat-server:latest
        container_name: vocechat
        restart: unless-stopped
        ports:
            - "8200:3000"
        volumes:
            - ./vocechat:/home/vocechat-server/data

            